apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rw81pp4gk-java-quarkus
  janus-idp.io/tekton: rw81pp4gk-java-quarkus
  backstage.io/kubernetes-id: rw81pp4gk-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rw81pp4gk-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
